version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  app:
    build: .
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: ["python", "ingest.py",  "validate.py"]
    environment:
      - MONGO_URI=mongodb://mongo:27017

volumes:
  mongo-data:
