version: "3.9"
services:
  mongo:
    image: mongo:7.0 
    container_name: mongo
    ports:
      - "27017:27017"  # Expose MongoDB port for local access
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data on the host via named volume

  app:
    build:
      context: .  
      dockerfile: docker/Dockerfile.ingest  # Path to Dockerfile for ingestion script
    depends_on:
      - mongo  # Wait for MongoDB to be ready before starting
    env_file: .env  # Load environment variables for ingestion script

  api:
    build:
      context: .  
      dockerfile: docker/Dockerfile.api  # Path to Dockerfile for FastAPI service
    ports:
      - "8000:8000"  # Expose FastAPI port to host machine
    depends_on:
      - mongo  # Ensure MongoDB is running before starting the API
    env_file: .env  # Load environment variables into API container

volumes:
  mongo-data:  # Named volume to persist MongoDB data
